apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: todoapp
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  accessModes:
  - ReadWriteMany
